<?php
return [
        'contact_id',
        'first_name',
        'last_name',
        'company',
        'email',
        'phone',
        'address',
        'city',
        'province',
        'postal_code',
        'country',
        'notes',
        'linkedin',
        'created_at',
        'last_modified',
        'is_customer',
        'delivery_date',
        'delivery_date',
        'tags'
];